
version: '3'
services:
  database:
    # Official Postgres image from DockerHub (we use the last version)
    image: 'postgres:latest'
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db-data/:/var/lib/postgresql/data/